; 繁體中文（正體中文）訊息檔 — 供 MemoTack 安裝程式使用
; 未翻譯的訊息會自動使用英文預設值

[LangOptions]
LanguageName=<7E41><9AD4><4E2D><6587>
LanguageID=$0404
LanguageCodePage=0

[Messages]
SetupAppTitle=安裝程式
SetupWindowTitle=安裝 - %1
UninstallAppTitle=解除安裝
UninstallAppFullTitle=解除安裝 %1
InformationTitle=資訊
ConfirmTitle=確認
ErrorTitle=錯誤
SetupLdrStartupMessage=這將會安裝 %1。要繼續嗎？
LdrCannotCreateTemp=無法建立暫存檔，安裝中止
LdrCannotExecTemp=無法執行暫存資料夾中的檔案，安裝中止
LastErrorMessage=%1.%n%n錯誤 %2：%3
SetupFileMissing=安裝資料夾中缺少檔案 %1。請修正此問題，或取得程式的新版本。
SetupFileCorrupt=安裝檔已損毀。請取得程式的新版本。
SetupFileCorruptOrWrongVer=安裝檔已損毀，或與此版本的安裝程式不相容。請修正此問題，或取得程式的新版本。
InvalidParameter=命令列參數無效：%n%n%1
SetupAlreadyRunning=安裝程式已在執行中。
WindowsVersionNotSupported=此程式不支援您電腦執行的 Windows 版本。
WinVersionTooLowError=此程式需要 %1 版本 %2 或更新。
AdminPrivilegesRequired=您必須以系統管理員身分登入才能安裝此程式。
PowerUserPrivilegesRequired=您必須以系統管理員或 Power Users 群組成員身分登入才能安裝此程式。
SetupAppRunningError=安裝程式偵測到 %1 正在執行中。%n%n請先關閉該程式的所有執行個體，然後按「確定」繼續，或按「取消」結束。
UninstallAppRunningError=解除安裝程式偵測到 %1 正在執行中。%n%n請先關閉該程式的所有執行個體，然後按「確定」繼續，或按「取消」結束。
PrivilegesRequiredOverrideTitle=選擇安裝模式
PrivilegesRequiredOverrideInstruction=選擇安裝模式
PrivilegesRequiredOverrideText1=%1 可以為所有使用者安裝（需要系統管理員權限），或只為您安裝。
PrivilegesRequiredOverrideText2=%1 可以只為您安裝，或為所有使用者安裝（需要系統管理員權限）。
PrivilegesRequiredOverrideAllUsers=為所有使用者安裝(&A)
PrivilegesRequiredOverrideAllUsersRecommended=為所有使用者安裝（建議選項）(&A)
PrivilegesRequiredOverrideCurrentUser=只為我安裝(&M)
PrivilegesRequiredOverrideCurrentUserRecommended=只為我安裝（建議選項）(&M)
ExitSetupTitle=結束安裝
ExitSetupMessage=安裝尚未完成。如果現在結束，程式將不會被安裝。%n%n您可以之後再次執行安裝程式來完成安裝。%n%n要結束安裝嗎？
AboutSetupMenuItem=關於安裝程式(&A)...
AboutSetupTitle=關於安裝程式
AboutSetupMessage=%1 版本 %2%n%3%n%n%1 首頁：%n%4
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安裝(&I)
ButtonOK=確定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全部皆是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全部皆否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=瀏覽(&B)...
ButtonWizardBrowse=瀏覽(&R)...
ButtonNewFolder=建立新資料夾(&M)
SelectLanguageTitle=選擇安裝語言
SelectLanguageLabel=選擇安裝過程要使用的語言。
ClickNext=按「下一步」繼續，或按「取消」結束安裝。
BrowseDialogTitle=瀏覽資料夾
BrowseDialogLabel=在下列清單中選擇資料夾，然後按「確定」。
NewFolderName=新資料夾
WelcomeLabel1=歡迎使用 [name] 安裝精靈
WelcomeLabel2=這將會在您的電腦上安裝 [name/ver]。%n%n建議您先關閉其他所有應用程式再繼續。
WizardSelectDir=選擇安裝位置
SelectDirDesc=要將 [name] 安裝在哪裡？
SelectDirLabel3=安裝程式會將 [name] 安裝到以下資料夾。
SelectDirBrowseLabel=按「下一步」繼續。若要選擇其他資料夾，請按「瀏覽」。
DiskSpaceGBLabel=至少需要 [gb] GB 的可用磁碟空間。
DiskSpaceMBLabel=至少需要 [mb] MB 的可用磁碟空間。
CannotInstallToNetworkDrive=無法安裝到網路磁碟機。
CannotInstallToUNCPath=無法安裝到 UNC 路徑。
InvalidPath=您必須輸入含磁碟機代號的完整路徑，例如：%n%nC:\APP%n%n或 UNC 路徑：%n%n\\伺服器\共用資料夾
InvalidDrive=您選取的磁碟機或 UNC 共用不存在或無法存取。請重新選擇。
DiskSpaceWarningTitle=磁碟空間不足
DiskSpaceWarning=安裝至少需要 %1 KB 的可用空間，但所選磁碟機只有 %2 KB 可用。%n%n仍要繼續嗎？
DirNameTooLong=資料夾名稱或路徑太長。
InvalidDirName=資料夾名稱無效。
BadDirName32=資料夾名稱不能包含下列任何字元：%n%n%1
DirExistsTitle=資料夾已存在
DirExists=資料夾：%n%n%1%n%n已存在。仍要安裝到該資料夾嗎？
DirDoesntExistTitle=資料夾不存在
DirDoesntExist=資料夾：%n%n%1%n%n不存在。要建立該資料夾嗎？
WizardSelectComponents=選擇元件
SelectComponentsDesc=要安裝哪些元件？
SelectComponentsLabel2=勾選想要安裝的元件；取消勾選不想安裝的元件。準備好後按「下一步」繼續。
FullInstallation=完整安裝
CompactInstallation=最小安裝
CustomInstallation=自訂安裝
ComponentSize1=%1 KB
ComponentSize2=%1 MB
ComponentsDiskSpaceGBLabel=目前的選擇至少需要 [gb] GB 磁碟空間。
ComponentsDiskSpaceMBLabel=目前的選擇至少需要 [mb] MB 磁碟空間。
WizardSelectTasks=選擇附加工作
SelectTasksDesc=要執行哪些附加工作？
SelectTasksLabel2=選擇安裝 [name] 時要執行的附加工作，然後按「下一步」。
WizardSelectProgramGroup=選擇開始選單資料夾
SelectStartMenuFolderDesc=要將程式捷徑放在哪裡？
SelectStartMenuFolderLabel3=安裝程式會在以下開始選單資料夾建立程式捷徑。
SelectStartMenuFolderBrowseLabel=按「下一步」繼續。若要選擇其他資料夾，請按「瀏覽」。
MustEnterGroupName=您必須輸入資料夾名稱。
GroupNameTooLong=資料夾名稱或路徑太長。
InvalidGroupName=資料夾名稱無效。
BadGroupName=資料夾名稱不能包含下列任何字元：%n%n%1
NoProgramGroupCheck2=不建立開始選單資料夾(&D)
WizardReady=準備安裝
ReadyLabel1=安裝程式已準備好將 [name] 安裝到您的電腦。
ReadyLabel2a=按「安裝」開始安裝，或按「上一步」檢視或變更設定。
ReadyLabel2b=按「安裝」開始安裝。
ReadyMemoUserInfo=使用者資訊：
ReadyMemoDir=安裝位置：
ReadyMemoType=安裝類型：
ReadyMemoComponents=選取的元件：
ReadyMemoGroup=開始選單資料夾：
ReadyMemoTasks=附加工作：
PreparingDesc=安裝程式正在準備將 [name] 安裝到您的電腦。
PreviousInstallNotCompleted=先前程式的安裝或移除尚未完成，需要重新啟動電腦才能完成。%n%n重新啟動後，請再次執行安裝程式以完成 [name] 的安裝。
CannotContinue=安裝程式無法繼續。請按「取消」結束。
ApplicationsFound=下列應用程式正在使用需要由安裝程式更新的檔案。建議您允許安裝程式自動關閉這些應用程式。
ApplicationsFound2=下列應用程式正在使用需要由安裝程式更新的檔案。建議您允許安裝程式自動關閉這些應用程式。安裝完成後，安裝程式會嘗試重新啟動它們。
CloseApplications=自動關閉這些應用程式(&A)
DontCloseApplications=不要關閉這些應用程式(&D)
ErrorCloseApplications=安裝程式無法自動關閉所有應用程式。建議您先關閉使用到相關檔案的應用程式再繼續。
WizardInstalling=安裝中
InstallingLabel=請稍候，安裝程式正在將 [name] 安裝到您的電腦。
FinishedHeadingLabel=[name] 安裝完成
FinishedLabelNoIcons=安裝程式已將 [name] 安裝到您的電腦。
FinishedLabel=安裝程式已將 [name] 安裝到您的電腦。您可以透過安裝的捷徑啟動應用程式。
ClickFinish=按「完成」結束安裝。
FinishedRestartLabel=為完成 [name] 的安裝，必須重新啟動您的電腦。要立即重新啟動嗎？
FinishedRestartMessage=為完成 [name] 的安裝，必須重新啟動您的電腦。%n%n要立即重新啟動嗎？
ShowReadmeCheck=是，我要檢視 README 檔案
YesRadio=是，立即重新啟動電腦(&Y)
NoRadio=否，我稍後再重新啟動電腦(&N)
RunEntryExec=執行 %1
RunEntryShellExec=檢視 %1
StatusClosingApplications=正在關閉應用程式...
StatusCreateDirs=正在建立資料夾...
StatusExtractFiles=正在解壓縮檔案...
StatusCreateIcons=正在建立捷徑...
StatusCreateIniEntries=正在建立 INI 項目...
StatusCreateRegistryEntries=正在建立登錄項目...
StatusRegisterFiles=正在註冊檔案...
StatusSavingUninstall=正在儲存解除安裝資訊...
StatusRunProgram=正在完成安裝...
StatusRestartingApplications=正在重新啟動應用程式...
StatusRollback=正在復原變更...
ErrorInternal2=內部錯誤：%1
ErrorFunctionFailedNoCode=%1 失敗
ErrorFunctionFailed=%1 失敗；錯誤碼 %2
ErrorFunctionFailedWithMessage=%1 失敗；錯誤碼 %2。%n%3
ErrorExecutingProgram=無法執行檔案：%n%1
ErrorOccurred=發生錯誤
UninstallNotFound="%1" 檔案不存在，無法解除安裝。
UninstallOpenError=無法開啟 "%1" 檔案，無法解除安裝
UninstallUnsupportedVer=此版本的解除安裝程式無法辨識解除安裝紀錄檔 "%1" 的格式，無法解除安裝
UninstallUnknownEntry=解除安裝紀錄中出現無法辨識的項目 (%1)
ConfirmUninstall=確定要完全移除 %1 及其所有元件嗎？
UninstallOnlyOnWin64=此安裝只能在 64 位元 Windows 上解除安裝。
OnlyAdminCanUninstall=此安裝只能由具有系統管理員權限的使用者解除安裝。
UninstallStatusLabel=正在從您的電腦移除 %1，請稍候。
UninstalledAll=%1 已成功從您的電腦移除。
UninstalledMost=%1 解除安裝完成。%n%n部分項目無法移除，您可以手動刪除。
UninstalledAndNeedsRestart=為完成 %1 的解除安裝，必須重新啟動您的電腦。%n%n要立即重新啟動嗎？
UninstallDataCorrupted="%1" 檔案已損毀，無法解除安裝。
ConfirmDeleteSharedFileTitle=移除共用檔案？
ConfirmDeleteSharedFile2=系統顯示下列共用檔案已不再被任何程式使用。要移除這個共用檔案嗎？%n%n如果仍有程式使用此檔案而它被移除，那些程式可能無法正常運作。若不確定，請選「否」；保留此檔案不會造成任何問題。
SharedFileNameLabel=檔案名稱：
SharedFileLocationLabel=位置：
WizardUninstalling=解除安裝狀態
StatusUninstalling=正在解除安裝 %1...
ShutdownBlockReasonInstallingApp=正在安裝 %1。
ShutdownBlockReasonUninstallingApp=正在解除安裝 %1。

[CustomMessages]
NameAndVersion=%1 版本 %2
AdditionalIcons=附加捷徑：
CreateDesktopIcon=建立桌面捷徑(&D)
CreateQuickLaunchIcon=建立快速啟動捷徑(&Q)
ProgramOnTheWeb=%1 網站
UninstallProgram=解除安裝 %1
LaunchProgram=啟動 %1
AssocFileExtension=將 %1 與 %2 檔案副檔名建立關聯(&A)
AssocingFileExtension=正在將 %1 與 %2 檔案副檔名建立關聯...
AutoStartProgramGroupDescription=啟動：
AutoStartProgram=自動啟動 %1
AddonHostProgramNotFound=在您選取的資料夾中找不到 %1。%n%n仍要繼續嗎？
